version: '3'

services:
  bluetixservice:
    image: bluetixservice
    build: .
    ports:
      - "9090:8080"
    environment:
      MYSQL_HOST: bluetixdb
      MYSQL_USER: root
      MYSQL_PASSWORD: Password123
      MYSQL_PORT: 3306

      RDS_MYSQL_HOST: bluetix-db.cnrxufwju1qq.ap-southeast-2.rds.amazonaws.com/bluetixdb
      RDS_MYSQL_USER: admin
      RDS_MYSQL_PASSWORD: BlueMonkey$
      RDS_MYSQL_PORT: 3306
      
      S3_SQL_HOST: ""
      S3_REGION_STATIC: ap-southeast-2
      S3_BUCKET: bluetixbucket
      S3_ACCESS_KEY: AKIATZYGZYDHQ3KY6MB3
      S3_SECRET_ACCESS_KEY: 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

      JWT_SECRET: RmdtiXkNbmt5eGU4GZBNUpfJiEffVQnU6xVjQKA6J0EZT4LQtxZOdAz0xam6i6uJ
        
    restart: on-failure
    
networks:
  bluetix-net:
    driver: bridge

volumes:
  volume1:
    external: false