name: CI for BluetixService

on:
  push:
    branches: [ "dev"]
  pull_request:
    branches: [ "dev"]

jobs:
  build:
    env:
      jwtSecret: ${{secrets.jwtSecret}}
      S3_ACCESS_KEY: ${{secrets.S3_ACCESS_KEY}}
      S3_SECRET_ACCESS_KEY: ${{secrets.S3_SECRET_ACCESS_KEY}}
      S3_REGION_STATIC: ${{secrets.S3_REGION_STATIC}}
      S3_BUCKET: ${{'bluetixbucket'}}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      id: jdk
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Set MYSQL for Tests
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql database: 'bluetixdb' # Optional, default value is "test". The specified database which will be create
        mysql root password: ${{'123'}} # Required if "mysql user" is empty, default is empty. The root superuser password
    - name: Set Environment Variable
      run: echo $jwtSecret
    - name: Run test Cases
      run: mvn test 
    - name: Build with Maven
      id: mvnpackage
      run: mvn -B package
