# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CICD for BluetixService

on:
  push:
    branches: [ "main",]
  pull_request:
    branches: [ "main"]

jobs:
  build:
    env:
      jwtSecret: ${{secrets.jwtSecret}}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      id: jdk
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Set Environment Variable
      run: echo $jwtSecret
    - name: Run test Cases
      run: mvn test 
    - name: Build with Maven
      id: mvnpackage
      run: mvn -B package
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker image
      if: steps.mvnpackage.outcome == 'success'
      uses: docker/build-push-action@v2
      with:
        context: ./
        push: true
        dockerfile: ./Dockerfile
        tags: 69iqrexgan/bluetixservice:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set permissions for private key
      run: echo "${{ secrets.AWS_PRIVATE_KEY }}" > key.pem; chmod 600 key.pem
    - name: Pull Docker image
      run: ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@ec2-13-211-240-56.ap-southeast-2.compute.amazonaws.com 'sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }} ;sudo docker pull 69iqrexgan/bluetixservice:latest'
    - name: Stop running container
      run: ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@ec2-13-211-240-56.ap-southeast-2.compute.amazonaws.com 'sudo docker stop bluetixservice || true'; ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@ec2-13-211-240-56.ap-southeast-2.compute.amazonaws.com 'sudo docker rm bluetixservice || true'
    - name: Run new container
      run: ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@ec2-13-211-240-56.ap-southeast-2.compute.amazonaws.com 'sudo docker run -d --name bluetixservice -p 80:8080 69iqrexgan/bluetixservice:latest'
    
